### PR TITLE
docs: fix links in Markdown files

### PR DESCRIPTION
**Pull request by KhudaDad414**
#### Description
this PR is supposed to fix all the [broken links](https://github.com/asyncapi/event-gateway/runs/6143316805?check_suite_focus=true) in markdown files across the repo.

### CODE REVIEW

**Comment by smoya** [comment]
@KhudaDad414 the link is not broken, at least when rendered in Github.

**Comment by KhudaDad414** [comment]
@smoya yes it works. But the validator can't validate it for some reason. So I changed it a little.

**Comment by smoya** [comment]
> @smoya yes it works. But the validator can't validate it for some reason. So I changed it a little.

I guess it complains because it is a relative link? Anyway, I'm happy merging this.

**Review by smoya — APPROVED** [review]

**Pull request merged**
